'use strict';

const CB = {
    MENU_HOME: 'menu:home',
    MENU_ACCOUNT: 'menu:minha_conta',
    CATALOG_VIEW: 'catalog:view',
    CART_VIEW: 'cart:view',
    CART_CLEAR: 'cart:clear',
    CHECKOUT_START: 'checkout:start',
    CHECKOUT_PROCESSING: 'checkout:processing',
    SEARCH_OPEN: 'search:open',
    FLASH_SALES: 'flash:sales',
    HELP_OPEN: 'help:open',
    HANORK_OPEN: 'hanork:open',
    DOWNLOADS_OPEN: 'downloads:open',
    USER_FAVORITES: 'user:favoritos',
    USER_AFFILIATE: 'user:afiliado',
    USER_SHARE: 'user:indicar',
    USER_COUPON: 'user:cupom',
    USER_REVIEWS: 'user:avaliacoes',
    SUBSCRIPTION_VIEW: 'subscription:view',
    SMM_HOME: 'smm:home',
    VIRTUO_HOME: 'virtuo:home',
    ORDER_LIST: 'order:list',
    ORDER_TRACK: 'order:track',
    ORDER_RESEND: 'order:resend',
    NOOP: 'noop',
    PAYMENT_PIX: (id) => `payment:pix:${id}`,
    PAYMENT_CARD: (id) => `payment:card:${id}`,
    PAYMENT_AFF: (id) => `payment:aff:${id}`,
    PAYMENT_WALLET: (id) => `payment:wallet:${id}`,
    PAYMENT_CHECK: (id) => `payment:check:${id}`,
};

const LEGACY_STATIC = {
    home: CB.MENU_HOME,
    cat: CB.CATALOG_VIEW,
    cart: CB.CART_VIEW,
    clr: CB.CART_CLEAR,
    minha_conta: CB.MENU_ACCOUNT,
    buscar_btn: CB.SEARCH_OPEN,
    flash_sales: CB.FLASH_SALES,
    help_btn: CB.HELP_OPEN,
    meus_favoritos: CB.USER_FAVORITES,
    assinar_premium: CB.SUBSCRIPTION_VIEW,
    minha_assinatura: CB.SUBSCRIPTION_VIEW,
    orders: CB.ORDER_LIST,
    rastrear_btn: CB.ORDER_TRACK,
    reenviar_btn: CB.ORDER_RESEND,
    cupom_btn: CB.USER_COUPON,
    meu_afiliado: CB.USER_AFFILIATE,
    compartilhar_btn: CB.USER_SHARE,
    minhas_avaliacoes: CB.USER_REVIEWS,
    checkout: CB.CHECKOUT_START,
    noop: CB.NOOP,
};

module.exports = { CB, LEGACY_STATIC };
