'use strict';

const CHECKOUT_DISCOUNT = Number(process.env.SUBSCRIPTION_CHECKOUT_DISCOUNT || '0.10');
const WELCOME_COUPON_PERCENT = Number(process.env.SUBSCRIPTION_WELCOME_COUPON_PERCENT || '20');
const WELCOME_COUPON_COUNT = Number(process.env.SUBSCRIPTION_WELCOME_COUPON_COUNT || '5');
const WELCOME_COUPON_DAYS = Number(process.env.SUBSCRIPTION_WELCOME_COUPON_DAYS || '30');
const PREMIUM_CASHBACK_PERCENT = Number(process.env.SUBSCRIPTION_CASHBACK_PERCENT || '10');
const BASE_CASHBACK_PERCENT = Number(process.env.CASHBACK_PERCENT || '5');

module.exports = {
    CHECKOUT_DISCOUNT: CHECKOUT_DISCOUNT > 0 && CHECKOUT_DISCOUNT <= 1 ? CHECKOUT_DISCOUNT : 0.10,
    WELCOME_COUPON_PERCENT: WELCOME_COUPON_PERCENT > 0 ? WELCOME_COUPON_PERCENT : 20,
    WELCOME_COUPON_COUNT: WELCOME_COUPON_COUNT > 0 ? Math.floor(WELCOME_COUPON_COUNT) : 5,
    WELCOME_COUPON_DAYS: WELCOME_COUPON_DAYS > 0 ? Math.floor(WELCOME_COUPON_DAYS) : 30,
    PREMIUM_CASHBACK_PERCENT: PREMIUM_CASHBACK_PERCENT > 0 ? PREMIUM_CASHBACK_PERCENT : 10,
    BASE_CASHBACK_PERCENT: BASE_CASHBACK_PERCENT > 0 ? BASE_CASHBACK_PERCENT : 5,
    REMINDER_DAYS_BEFORE: Number(process.env.SUBSCRIPTION_REMINDER_DAYS || '3'),
};
