'use strict';

/** Rótulos SMM — emojis alinhados ao padrão Hanork (menuCopy / navKeyboard). */
module.exports = {
    HOME: '📈 Serviços SMM',
    CATALOG: '🛍️ Catálogo',
    MENU: '🏠 Menu',
    BUY: '💳 Comprar',
    BACK: '🔙 Voltar',
    PLATFORMS: '📱 Plataformas',
    CATEGORIES: '📂 Categorias',
    PREV: '◀️ Anterior',
    NEXT: '▶️ Próxima',
    MY_ORDERS: '📦 Meus pedidos',
    NEW_ORDER: '➕ Novo pedido',
    TRACK_ORDER: '📦 Acompanhar pedido',
    VIEW_ORDER: '👁️ Ver pedido',
    TICKET: '🎫 Abrir ticket',
    CHANGE_LINK: '🔗 Alterar link',
    CHANGE_QTY: '🔢 Quantidade',
    OTHER_QTY: '🔢 Outra quantidade',
    CHANGE_SERVICE: '🔄 Trocar serviço',
    SERVICE: '📈 Serviço',
    CANCEL: '❌ Cancelar',
    CANCEL_ORDER: '❌ Cancelar pedido',
    CONTINUE_PAY: '💳 Continuar pagamento',
    OPEN_STORE: '🛍️ Abrir catálogo',
    OPEN_SMM: '📈 Serviços SMM',
    OPEN_SHOP: '🛍️ Abrir catálogo',
    REFILL: '🔄 Solicitar reposição',
    OTHER_SERVICE: '🔄 Outro serviço',
    BACK_ORDER: '🔙 Voltar ao pedido',
    CONFIRM_CANCEL: '✅ Sim, cancelar',
    BUY_SERVICES: '📈 Comprar serviços',
    REFRESH: '🔄 Atualizar',
    TERMS: '📜 Termos de uso',
};
