#!/usr/bin/env bash
set -euo pipefail
SRC=/mnt/c/Users/boots/Downloads/hanork
DST=/home/vendetta/hanork
files=(
  src/modules/payment/cardAutoPoll.js
  src/modules/payment/paymentCheckUtils.js
  src/services/PaymentCheckService.js
  src/telegram/messageDelivery.js
  src/utils/safeTelegram.js
  src/telegram/Msg.js
  src/utils/imageFileValidation.js
  src/utils/productPhoto.js
  src/telegram/screenPhoto.js
  src/telegram/menuPhoto.js
  src/telegram/Msg.js
  src/telegram/callbacks/payment/paymentUi.js
  src/app/startBot.js
  scripts/test-screen-photo-validation.js
  src/core/UserHandlers.js
  src/telegram/admin/adminPanelUi.js
  src/telegram/commands/admin/shared.js
  src/telegram/commands/admin/productWizardHandlers.js
  src/bot/helpers/productAdminBridge.js
  src/telegram/commands/user/flashGiveawayHandlers.js
  src/telegram/commands/user/userWelcomeTour.js
  src/telegram/downloads/downloadsHandlers.js
  src/telegram/downloads/downloadsNav.js
  src/telegram/commands/playCommands.js
  src/telegram/commands/tiktokCommands.js
  src/telegram/commands/youtubeCommands.js
  src/telegram/commands/instagramCommands.js
  src/modules/smm/helpers/smmPanelUi.js
  src/modules/affiliate/AffiliatePanels.js
  src/modules/affiliate/AffiliateCore.js
  src/services/AffiliateCommissionService.js
  src/services/SalesReferenceChannelService.js
  src/config/BackupManager.js
  scripts/test-panel-photo-policy.js
  src/bot/createBotContext.js
  src/modules/payment/PaymentService.js
  src/modules/payment/MpAdapter.js
  src/telegram/callbacks/payment/registerPaymentActions.js
  src/telegram/callbacks/payment/paymentUi.js
  src/modules/smm/smmAccess.js
  src/modules/smm/smmConfig.js
  src/modules/smm/utils/smmLabels.js
  src/modules/smm/handlers/smmUiHandlers.js
  src/modules/smm/handlers/smmWizardHandler.js
  src/telegram/menus/MenuKeyboards.js
  src/telegram/menus/menuCopy.js
  src/config/hanork-router-copy.js
  src/services/hanork-ai/HanorkUniversalRegistry.js
  src/config/broadcastConfig.js
  src/config/campaignConfig.js
  src/config/securityEnv.js
  src/modules/payment/webhookPaymentDedup.js
  src/modules/payment/webhookRedisDedup.js
  src/config/database-sqlite.js
  src/services/broadcastPvQueue.js
  src/services/BroadcastService.js
  src/services/BroadcastAdaptiveThrottle.js
  src/services/AutoBroadcastService.js
  src/services/campaign/CampaignStore.js
  src/services/campaign/CampaignOrchestrator.js
  src/services/campaign/campaignTimeWindows.js
  src/services/campaign/campaignContent.js
  src/services/broadcastRateLimit.js
  src/modules/queue/jobs/broadcastJob.js
  src/modules/health/bootMetrics.js
  src/modules/health/HealthCheck.js
  src/plugins/zero-divu/campaignWaSync.js
  src/plugins/zero-divu/hanorkAutoSync.js
  src/plugins/zero-divu/promo.js
  scripts/test-campaign-suite.js
  scripts/check-campaign-status.js
  scripts/validate-campaign-live.sh
  scripts/deploy-checklist.sh
  scripts/test-dashboard-tenant-scope.js
  scripts/test-dashboard-csrf.js
  scripts/test-webhook-redis-dedup.js
  scripts/test-mp-webhook-handler.js
  scripts/test-order-metrics.js
  scripts/test-observability-config.js
  scripts/test-prometheus-metrics.js
  scripts/test-admin-utils.js
  scripts/test-security-suite.js
  scripts/test-mp-webhook-replay-integration.js
  scripts/replay-mp-webhook-staging.sh
  scripts/sync-webhook-wsl.sh
  src/modules/payment/mpWebhookHandler.js
  src/app/createServer.js
  src/jobs/startupRecovery.js
  src/app/startBot.js
  src/bot/bootstrap/createGroupBroadcastStack.js
  src/telegram/middlewares/mainMiddleware.js
  src/telegram/middlewares/forwardSpamMiddleware.js
  src/telegram/commands/aiCommands.js
  src/telegram/middlewares/textCatchAllHandler.js
  src/telegram/handlers/productEditTextHandler.js
  src/telegram/handlers/productWizardTextHandler.js
  src/telegram/handlers/productAdminFlowGuard.js
  src/bot/helpers/productAdminBridge.js
  src/telegram/commands/admin/productCommands.js
  src/telegram/commands/admin/productWizardHandlers.js
  scripts/test-menu-photo-delivery.js
  src/telegram/middlewares/productMediaHandler.js
  src/services/HanorkInvokeRouter.js
  src/services/hanork-ai/HanorkIntentEngine.js
  src/telegram/commands/aiCommands.js
  src/services/TelegramEventAuditService.js
  src/telegram/middlewares/telegramEventRouterMiddleware.js
  src/telegram/events/TelegramEventClassifier.js
  src/telegram/events/groupEvents.js
  src/telegram/commands/user/startHandler.js
  src/config/salesReferenceChannel.js
  src/telegram/referenceChannelGuard.js
  src/telegram/downloadsDailyLimit.js
  src/telegram/downloadsGuard.js
  src/telegram/downloads/downloadsUi.js
  src/telegram/groupGuard.js
  src/telegram/menus/menuCopy.js
  src/telegram/menus/MenuKeyboards.js
  scripts/test-ref-channel-downloads.js
  src/config/config.js
  src/bot/createBotContext.js
  src/services/GroupSettingsService.js
  src/modules/user/UserAccountPanels.js
  src/modules/subscription/CustomerSubscriptionService.js
  src/telegram/play/playUi.js
  src/telegram/tiktok/tiktokUi.js
  src/telegram/youtube/youtubeUi.js
  src/telegram/instagram/instagramUi.js
  src/services/ZeroTwoAiService.js
  src/telegram/events/groupEvents.js
  src/jobs/schedulers/postSaleFollowUpScheduler.js
  src/telegram/commands/botCommandsCatalog.js
  src/telegram/commands/groups.js
  src/telegram/commands/idCommands.js
  src/bot/registerHanorkBot.js
  src/services/NewMemberNotifyService.js
  scripts/test-telegram-event-classifier.js
  scripts/test-telegram-event-audit.js
  src/data/smmPromoThemes.json
  src/data/hanorkPromoThemes.json
  src/data/hanorkBroadcastVariants.js
  src/data/smmBroadcastVariants.js
  src/utils/promoMediaPaths.js
  src/utils/promoMediaValidation.js
  src/utils/wslMediaPath.js
  scripts/hanork-boot.sh
  scripts/apply-wsl-media-env.sh
  scripts/fix-caminho-fotos.sh
  scripts/test-promo-media-pairing.js
  scripts/setup-promo-media-dirs.sh
)
for f in "${files[@]}"; do
  if [[ -f "$SRC/$f" ]]; then
    install -D -m 644 "$SRC/$f" "$DST/$f"
    echo "OK $f"
  else
    echo "MISSING $f" >&2
    exit 1
  fi
done
echo "Sync complete."
