'use strict';

/**
 * B3 — deps do painel admin (registerAdminHandlers).
 */
function buildAdminDeps(deps) {
    const {
        prisma,
        dbRaw,
        Markup,
        isAdmin,
        ADMIN_HTML,
        Msg,
        Menu,
        logger,
        deferBackground,
        bot,
        bannedUsers,
        antiSpam,
        backup,
        broadcastMode,
        addProductMode,
        adminMsgTarget,
        editProductMode,
        giveawayMode,
        getMaintenanceMode,
        setMaintenanceMode,
        autoBroadcastService,
        broadcastService,
        CONFIG,
        AUTO_BROADCAST_INTERVAL_MS,
        formatBroadcastInterval,
        executeFullBroadcast,
        emailService,
        UserEmailService,
        loadProducts,
        executeBroadcast,
        groupSettings,
        groupService,
        sendAdminPanelWithPhoto,
        editAdminPanel,
        invalidateProductCache,
        invalidateBotUsername,
        formatTimer,
        carrinhos,
        UserService,
        AuditService,
        sendMainMenu,
        deliverProducts,
        payAffiliateCommission,
        showUsers,
        activeChats,
        openTicketChat,
        closeTicketChat,
        ticketCloseKeyboard,
        confirmarSaldoReservado,
        pedirAvaliacao,
        buildGiveawaysPanel,
        joinChatAwaiting,
        botSession,
        sessionNote,
        syncBusinessLinksFromSettings,
    } = deps;

    return {
        prisma,
        dbRaw,
        Markup,
        isAdmin,
        ADMIN_HTML,
        Msg,
        Menu,
        logger,
        deferBackground,
        bot,
        bannedUsers,
        antiSpam,
        backup,
        broadcastMode,
        addProductMode,
        adminMsgTarget,
        editProductMode,
        giveawayMode,
        getMaintenanceMode,
        setMaintenanceMode,
        getAutoBroadcastEnabled: () => autoBroadcastService.isEnabled(),
        setAutoBroadcastEnabled: (v) => autoBroadcastService.setEnabled(v),
        getAutoBroadcastLastSent: () => autoBroadcastService.getLastSent(),
        getAutoBroadcastCount: () => autoBroadcastService.getCount(),
        getAutoBroadcastRunning: () => autoBroadcastService.isCycleRunning() || broadcastService.isRunning,
        getAutoBroadcastLastSummary: () => autoBroadcastService.getLastSummary(),
        autoBroadcastService,
        runAutoBroadcastNow: () => {
            const { runFullDivulgacaoCycle } = require('../../plugins/zero-divu/fullDivulgacao');
            return runFullDivulgacaoCycle(
                {
                    autoBroadcastService,
                    broadcastService,
                    CONFIG,
                    loadProducts,
                    prisma,
                    logger,
                },
                'manual'
            );
        },
        runBridgePromoNow: () => autoBroadcastService.runBridgePromoOnly('manual_bridge'),
        runBridgePromoAfterBot: (payload) => autoBroadcastService.runBridgePromoAfterBot(payload),
        CONFIG,
        AUTO_BROADCAST_INTERVAL: AUTO_BROADCAST_INTERVAL_MS,
        formatBroadcastInterval,
        executeFullBroadcast,
        emailService,
        UserEmailService,
        loadProducts,
        executeBroadcast,
        broadcastService,
        groupSettings,
        groupService,
        sendAdminPanelWithPhoto,
        editAdminPanel,
        invalidateProductCache,
        invalidateBotUsername,
        formatTimer,
        carrinhos,
        UserService,
        AuditService,
        sendMainMenu,
        deliverProducts,
        payAffiliateCommission,
        showUsers,
        activeChats,
        openTicketChat,
        closeTicketChat,
        ticketCloseKeyboard,
        confirmarSaldoReservado,
        pedirAvaliacao,
        buildGiveawaysPanel,
        joinChatAwaiting,
        botSession,
        sessionNote,
        appendSessionDiscardedNote: (text, cleared) => sessionNote(text, cleared),
        syncBusinessLinks: syncBusinessLinksFromSettings,
    };
}

module.exports = { buildAdminDeps };
